kind: pipeline
name: default

steps:
  - name: greet
    image: golang:1.10.7-alpine3.8
    commands:
      - echo "-- Drone command"
      - go version 

  - name: build
    image: golang:1.10.7-alpine3.8
    commands:
      - echo "-- Build the dang thing"
      - go version
      - go run main.go

  - name: dotnet-build
    image: plugins/docker
    settings:
      repo: mcr.microsoft.com/dotnet/core/samples
      dry_run: true

